
package com.turkcelltech.mf.tpay.web.provision;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProvisionServicesImplService", targetNamespace = "http://provision.web.tpay.mf.turkcelltech.com/", wsdlLocation = "META-INF/wsdl/ProvisionServicesImplService.wsdl")
public class ProvisionServicesImplService
    extends Service
{

    private final static URL PROVISIONSERVICESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROVISIONSERVICESIMPLSERVICE_EXCEPTION;
    private final static QName PROVISIONSERVICESIMPLSERVICE_QNAME = new QName("http://provision.web.tpay.mf.turkcelltech.com/", "ProvisionServicesImplService");

    static {
        PROVISIONSERVICESIMPLSERVICE_WSDL_LOCATION = com.turkcelltech.mf.tpay.web.provision.ProvisionServicesImplService.class.getClassLoader().getResource("META-INF/wsdl/ProvisionServicesImplService.wsdl");
        WebServiceException e = null;
        if (PROVISIONSERVICESIMPLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ProvisionServicesImplService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PROVISIONSERVICESIMPLSERVICE_EXCEPTION = e;
    }

    public ProvisionServicesImplService() {
        super(__getWsdlLocation(), PROVISIONSERVICESIMPLSERVICE_QNAME);
    }

    public ProvisionServicesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROVISIONSERVICESIMPLSERVICE_QNAME, features);
    }

    public ProvisionServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, PROVISIONSERVICESIMPLSERVICE_QNAME);
    }

    public ProvisionServicesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROVISIONSERVICESIMPLSERVICE_QNAME, features);
    }

    public ProvisionServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProvisionServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProvisionService
     */
    @WebEndpoint(name = "ProvisionServicesImplPort")
    public ProvisionService getProvisionServicesImplPort() {
        return super.getPort(new QName("http://provision.web.tpay.mf.turkcelltech.com/", "ProvisionServicesImplPort"), ProvisionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProvisionService
     */
    @WebEndpoint(name = "ProvisionServicesImplPort")
    public ProvisionService getProvisionServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://provision.web.tpay.mf.turkcelltech.com/", "ProvisionServicesImplPort"), ProvisionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROVISIONSERVICESIMPLSERVICE_EXCEPTION!= null) {
            throw PROVISIONSERVICESIMPLSERVICE_EXCEPTION;
        }
        return PROVISIONSERVICESIMPLSERVICE_WSDL_LOCATION;
    }

}
